spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/carsproject
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  jwt:
    secret: Q2xhdmVTZWNyZXRhMjAyM0RlbW9zU2VjdXRpcnkkJA==
    expiration: 28800000
